name: Prebuild

on:
  push:
    branches: [ "main", "dev" ]
jobs:
  build:
    env:
      IMAGE_NAME: Lappy.Cluster
      VERSION: 1.0.${{ github.run_number }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${{ env.VERSION }}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${{ env.VERSION }} --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${{ env.VERSION }} --no-build --output .
    - name: Push
      run: dotnet nuget push *.${{ env.VERSION }}.nupkg --source https://nuget.pkg.github.com/abutor/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
